# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b1cff5074e778367ba46dec3c446ad9f1923096fc90603d2dd7c890937957dcd66467aa283f311a72938bbc55f6831b17400844e139984457f34c1403d26e22

test:
  secret_key_base: 9dd3dcb82e9255e13a857f9becde164ae7ace4ad535ed346d6eb3c4a4b4b242aa49f78ad6d901c640de79a2d11ea6c28e0d581afef23a0e77a265c11e30f76bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
